//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzDSC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzDSC.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string UI_Caption_ConfirmDelete {
            get {
                return ResourceManager.GetString("UI_Caption_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string UI_Caption_Done {
            get {
                return ResourceManager.GetString("UI_Caption_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string UI_Caption_Error {
            get {
                return ResourceManager.GetString("UI_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete selected configuration item because following roles using it:.
        /// </summary>
        internal static string UI_Text_CannotDeleteRoles {
            get {
                return ResourceManager.GetString("UI_Text_CannotDeleteRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete selected role because following servers/groups using it:.
        /// </summary>
        internal static string UI_Text_CannotDeleteServersGroups {
            get {
                return ResourceManager.GetString("UI_Text_CannotDeleteServersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration item.
        /// </summary>
        internal static string UI_Text_ConfigurationItemC {
            get {
                return ResourceManager.GetString("UI_Text_ConfigurationItemC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration item.
        /// </summary>
        internal static string UI_Text_ConfigurationItemL {
            get {
                return ResourceManager.GetString("UI_Text_ConfigurationItemL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete selected .
        /// </summary>
        internal static string UI_Text_DoYouWantToDelete {
            get {
                return ResourceManager.GetString("UI_Text_DoYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string UI_Text_GroupL {
            get {
                return ResourceManager.GetString("UI_Text_GroupL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module installation completed!.
        /// </summary>
        internal static string UI_Text_ModuleInstallComplete {
            get {
                return ResourceManager.GetString("UI_Text_ModuleInstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string UI_Text_RoleL {
            get {
                return ResourceManager.GetString("UI_Text_RoleL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role or group.
        /// </summary>
        internal static string UI_Text_RoleOrGroupC {
            get {
                return ResourceManager.GetString("UI_Text_RoleOrGroupC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with same name already exists!.
        /// </summary>
        internal static string UI_Text_SameAlreadyExists {
            get {
                return ResourceManager.GetString("UI_Text_SameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        internal static string UI_Text_ServerL {
            get {
                return ResourceManager.GetString("UI_Text_ServerL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server or group.
        /// </summary>
        internal static string UI_Text_ServerOrGroupC {
            get {
                return ResourceManager.GetString("UI_Text_ServerOrGroupC", resourceCulture);
            }
        }
    }
}
